# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e7e767a5e1d09366688f75433baa82e21a65ddc625b21ef4dc2ccd61cc8a9466cfa182624c4b3e8349c9c88ed7d93dcb1bdbb70dfdf1593429072e39057d746

test:
  secret_key_base: 08d9f1fd6eedd892356371a64ad2e8de81e3e8acee6927331d779503e97f9db880681d4e1ad8b91bfba05aab390d6a4e69855f537938faa25f655bce6e8cdc7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
